### PR TITLE
Update ci. Fix build.

### PR DESCRIPTION
**Pull request by Neargye**
* Add more compiler
* Add parallel cmake run on travis
* Some clean-up

### CODE REVIEW

**Comment by Neargye** [comment]
why travis does not build the pull request?

**Comment by Neargye** [comment]
* Add  g++4.8/g++4.9/g++8
* Add xcode
* Add clang6.0
* Add Visual Studio 9 2008
* Add parallel cmake run on travis

Problem:
* It's a problem with the build on g++4.8 and g++4.9.
* And test fail in Xcode8 and Xcode9. [It's look like for xcode need use c++1z instead c++17](https://stackoverflow.com/questions/48597840/how-to-use-the-available-c17-flags-from-xcode-in-terminal)
* It's a problem with the build on Visual Studio 9 2008

**Comment by martinmoene** [comment]
Some remarks:

- test/CMakeLists.txt: needs AppleClang handling?
- string_view.hpp(495): `return assert(), expr` for constexpr apparently not acceptable for GCC 4.
- test/string_view.t.cpp: vec.data() => &vec[0] or cont_data(vec) to support <=msvc 9.
- Readme.md: msvc8 tested separately before and might (still) work.

This work is a bit hard to assess from my phone. I'll only be able to have good look at it after the weekend.

**Comment by Neargye** [comment]
* add data(vec) to support <=msvc 9. 
msvc 9 x64 fail. appveyor do not support?
* handling AppleClang in test/CMakeLists.txt. Now set c++1z flag, later if it is will support (Xcode10 ?),  c++17 flag will be set.
Xcode8/Xcode9 pass.

**Comment by martinmoene** [comment]
@neargye, these are nice improvements and additions.

I see you were able to follow my 'spatious' writing style (safe perhaps for `set(CMAKE_VERBOSE_MAKEFILE ON)`)

For msvc I can see some merit in using `/std:...` over `-std:...` to set msvc apart from other compilers, however I use  `-std:...`in many other projects and may want to keep it this way for the time being. My thinking was to focus on the similarities, not the gratuitous differences.

**Comment by Neargye** [comment]
* Fix gcc check. __GNUC__ defined if clang compiler.
* Draft fix gcc < 5 build

**Comment by Neargye** [comment]
* Sync Readme
* Remove `#endif // nssv_BETWEEN( nssv_COMPILER_GNUC_VERSION, 1, 500 )` comment

**Comment by martinmoene** [comment]
Thanks @Neargye !

**Pull request merged**
