### PR TITLE
added define to build without streams

### PR DESCRIPTION
**Pull request by theShmoo**
Hello! Thanks for your great library.

I need to use your library in an Intel SGX Enclave where we can't use standard streams (for security reasons).

In order to use your library I needed to exclude those lines from the header

### CODE REVIEW

**Comment by martinmoene** [comment]
Hi @theShmoo ,

Thanks for your input.

I'll likely implement these changes myself and perhaps use a configuration flag like `nssv_CONFIG_NO_STREAM_INSERTION`.

Files to update:
- README.md
- test/string-view.t.cpp
- include/nonstd/string_view.hpp

**Comment by theShmoo** [comment]
Thanks! Can I help you with anything?

**Comment by martinmoene** [comment]
Sure, if you like to update this PR into the direction of the suggestion above, that would certainly be of help :)

**Comment by theShmoo** [comment]
I updated the requested files 👍

**Comment by martinmoene** [comment]
Thanks @theShmoo ,

Looks good... 

However, there's something I forgot to warn for: trailing double spaces in `README.md`'s markdown are significant (see [`.editorconfig`](https://github.com/martinmoene/string-view-lite/blob/2abb8ead9c51a28c087109ef842754bc52537001/.editorconfig#L15)) and there are quite a lot of them. I'd appreciate it if you could you revert those to as they were before.

Thanks for your help.

**Comment by theShmoo** [comment]
Will do! Sorry for the auto formatting. Forgot to deactivate.

Martin Moene ***@***.***> schrieb am Sa., 24. Apr. 2021,
14:01:

**Comment by theShmoo** [comment]
Thank you very much for your support!

**Comment by martinmoene** [comment]
You're welcome, thank you too :)

**Pull request merged**
